name: cicd
on: [push] 
jobs:
  common:
    uses: joindevops-actions/reusable-workflows/.github/workflows/common.yaml@main
    with:
      project: roboshop
      component: catalogue
      app_type: nodejs
